const mongoose = require("mongoose");

const ArticleSchema = new mongoose.Schema(
  {
    title: String,
    author: String,
    url: String,

    // Original scraped content (unchanged)
    originalContent: String,
    // Updated content generated by LLM
    updatedContent: String,
    // content field kept for backward-compatibility (current shown content)
    content: String,
    references: [String]  // Google reference links (Phase-2)
  },
  { timestamps: true }
);

module.exports = mongoose.model("Article", ArticleSchema);
